### ISSUE TITLE
amd64.inl triggers warning C4706

### ISSUE THREAD

**Issue by MathiasMagnus** [ROCm-Developer-Tools/HIP-CPU#2]
Using HIP-CPU with MSVC and compiling with /W4 triggers the following warning within the library sources when consuming HIP-CPU:
```
external\libco\amd64.inl(134) : warning C4706: assignment within conditional expression
```
If the behavior really is intended (I couldn't tell at a first glance), please suppress warning locally.

Since the library partly aims at helping debugging device code, it were nice if I could get all the help I can get from the compiler (`/W4`) and the library wouldn't increase diagnostic noise. I know it isn't easy compiling cleanly under `/W4` but it is much appreciated.

**Comment by AlexVlx** [comment]
@MathiasMagnus thank you for reporting this, I believe it should be fixed now. In general, I'd very much like it if we kept it as clean / warning-free as possible - at the moment there are still some leftovers that I've not addressed, but since the library is fairly small itself there's little to no reason to add noise. Please, do let me know if it's still bothering you.
